### ISSUE TITLE
자동 로그인이 풀림

### ISSUE THREAD

**Issue by dittos** [dittos/animeta#27]
왜죠?

**Comment by EiNi** [comment]
왤까요?

**Comment by dittos** [comment]
세션 엔진을 signed_cookies로 변경. 지켜보는 중

**Comment by EiNi** [comment]
그러나 풀린다고 합니다 orz

**Comment by dittos** [comment]
@EiNi 일단 한번은 풀렸을 거고 다음에도 또 풀리면 알랴주세요~

**Comment by EiNi** [comment]
퇴근해보니 풀려있네요 하악... 크롬 확장기능이랑 충돌나는 게 있는지
